meals = [
    {
        "name": "Shakshuka",
        "main_ingredients": ["eggs", "tomatoes", "onion", "bell pepper"],
        "optional_ingredients": ["feta cheese", "parsley", "cumin", "paprika"],
        "meal_time": "breakfast",
        "time_required": 25,
        "servings": 2,
        "health_flags": {
            "vegetarian_friendly": True,
            "gluten_free_friendly": True,
            "diabetes_friendly": True,
            "vegan_friendly": False,
            "low_carb_friendly": True,
        },
        "recipe": {
            "instructions": [
                "Heat olive oil in a large skillet over medium heat",
                "Add diced onion and bell pepper, cook until softened",
                "Add crushed tomatoes, cumin, paprika, salt and pepper",
                "Simmer for 10-15 minutes until sauce thickens",
                "Make wells in the sauce and crack eggs into them",
                "Cover and cook until egg whites are set but yolks are runny",
                "Garnish with feta cheese and parsley",
            ],
            "cooking_tips": "Don't overcook the eggs - runny yolks are traditional",
        },
    },
    {
        "name": "Hummus Bowl",
        "main_ingredients": ["chickpeas", "tahini", "lemon juice", "olive oil"],
        "optional_ingredients": ["garlic", "cucumber", "tomatoes", "pita bread"],
        "meal_time": "lunch",
        "time_required": 15,
        "servings": 2,
        "health_flags": {
            "vegetarian_friendly": True,
            "gluten_free_friendly": True,
            "diabetes_friendly": True,
            "vegan_friendly": True,
            "low_carb_friendly": False,
        },
        "recipe": {
            "instructions": [
                "Drain and rinse chickpeas, reserve some liquid",
                "In food processor, blend chickpeas with tahini, lemon juice, and garlic",
                "Add olive oil and chickpea liquid gradually until smooth",
                "Season with salt and pepper",
                "Serve in bowl, drizzle with olive oil",
                "Top with diced cucumber, tomatoes, and serve with pita",
            ],
            "cooking_tips": "Reserve chickpea liquid to adjust consistency",
        },
    },
    {
        "name": "Chicken Fried Rice",
        "main_ingredients": ["rice", "chicken breast", "eggs", "soy sauce"],
        "optional_ingredients": ["green onions", "garlic", "ginger", "sesame oil"],
        "meal_time": "dinner",
        "time_required": 20,
        "servings": 3,
        "health_flags": {
            "vegetarian_friendly": False,
            "gluten_free_friendly": False,
            "diabetes_friendly": False,
            "vegan_friendly": False,
            "low_carb_friendly": False,
        },
        "recipe": {
            "instructions": [
                "Cook rice and let it cool (preferably day-old rice)",
                "Cut chicken into small pieces and season",
                "Heat oil in wok or large pan over high heat",
                "Scramble eggs and set aside",
                "Stir-fry chicken until cooked through",
                "Add rice, breaking up clumps",
                "Add soy sauce, garlic, ginger",
                "Return eggs to pan, add green onions",
                "Drizzle with sesame oil before serving",
            ],
            "cooking_tips": "Use day-old rice for best texture",
        },
    },
    {
        "name": "Greek Salad",
        "main_ingredients": ["tomatoes", "cucumber", "red onion", "feta cheese"],
        "optional_ingredients": ["olives", "oregano", "olive oil", "red wine vinegar"],
        "meal_time": "lunch",
        "time_required": 10,
        "servings": 2,
        "health_flags": {
            "vegetarian_friendly": True,
            "gluten_free_friendly": True,
            "diabetes_friendly": True,
            "vegan_friendly": False,
            "low_carb_friendly": True,
        },
        "recipe": {
            "instructions": [
                "Chop tomatoes into wedges",
                "Slice cucumber and red onion",
                "Combine vegetables in large bowl",
                "Add crumbled feta cheese and olives",
                "Whisk olive oil with red wine vinegar",
                "Pour dressing over salad",
                "Sprinkle with oregano",
                "Let sit for 10 minutes before serving",
            ],
            "cooking_tips": "Let salad marinate to develop flavors",
        },
    },
    {
        "name": "Beef Stir Fry",
        "main_ingredients": ["beef strips", "broccoli", "bell peppers", "garlic"],
        "optional_ingredients": ["ginger", "soy sauce", "oyster sauce", "sesame oil"],
        "meal_time": "dinner",
        "time_required": 15,
        "servings": 3,
        "health_flags": {
            "vegetarian_friendly": False,
            "gluten_free_friendly": False,
            "diabetes_friendly": True,
            "vegan_friendly": False,
            "low_carb_friendly": True,
        },
        "recipe": {
            "instructions": [
                "Cut beef into thin strips against the grain",
                "Heat oil in wok over high heat",
                "Stir-fry beef until just cooked, remove",
                "Add broccoli and bell peppers, stir-fry until crisp-tender",
                "Add garlic and ginger, stir for 30 seconds",
                "Return beef to pan",
                "Add soy sauce and oyster sauce",
                "Toss everything together and serve immediately",
            ],
            "cooking_tips": "Keep heat high and work quickly for best results",
        },
    },
    {
        "name": "Vegetable Curry",
        "main_ingredients": [
            "coconut milk",
            "curry powder",
            "onion",
            "mixed vegetables",
        ],
        "optional_ingredients": ["garlic", "ginger", "cilantro", "rice"],
        "meal_time": "breakfast",
        "time_required": 30,
        "servings": 4,
        "health_flags": {
            "vegetarian_friendly": True,
            "gluten_free_friendly": True,
            "diabetes_friendly": True,
            "vegan_friendly": True,
            "low_carb_friendly": False,
        },
        "recipe": {
            "instructions": [
                "Heat oil in large pot over medium heat",
                "Sauté onion, garlic, and ginger until fragrant",
                "Add curry powder and cook for 1 minute",
                "Add mixed vegetables and stir to coat",
                "Pour in coconut milk and bring to simmer",
                "Cover and cook until vegetables are tender",
                "Season with salt and pepper",
                "Garnish with cilantro and serve with rice",
            ],
            "cooking_tips": "Adjust curry powder to taste preference",
        },
    },
    {
        "name": "Tuna Salad Wrap",
        "main_ingredients": ["canned tuna", "tortilla", "lettuce", "mayonnaise"],
        "optional_ingredients": ["celery", "red onion", "tomatoes", "avocado"],
        "meal_time": "snack",
        "time_required": 10,
        "servings": 1,
        "health_flags": {
            "vegetarian_friendly": False,
            "gluten_free_friendly": False,
            "diabetes_friendly": True,
            "vegan_friendly": False,
            "low_carb_friendly": False,
        },
        "recipe": {
            "instructions": [
                "Drain tuna and flake into bowl",
                "Add diced celery and red onion",
                "Mix in mayonnaise until well combined",
                "Season with salt and pepper",
                "Lay tortilla flat and add lettuce",
                "Spoon tuna mixture over lettuce",
                "Add tomato slices and avocado",
                "Roll tightly and cut in half",
            ],
            "cooking_tips": "Pat vegetables dry to prevent soggy wrap",
        },
    },
    {
        "name": "Pancakes",
        "main_ingredients": ["flour", "eggs", "milk", "baking powder", "onion"],
        "optional_ingredients": ["sugar", "vanilla", "butter", "maple syrup"],
        "meal_time": "breakfast",
        "time_required": 15,
        "servings": 3,
        "health_flags": {
            "vegetarian_friendly": True,
            "gluten_free_friendly": False,
            "diabetes_friendly": False,
            "vegan_friendly": False,
            "low_carb_friendly": False,
        },
        "recipe": {
            "instructions": [
                "Mix flour, baking powder, sugar, and salt in bowl",
                "In separate bowl, whisk eggs, milk, and vanilla",
                "Pour wet ingredients into dry ingredients",
                "Mix until just combined (lumps are okay)",
                "Heat griddle or pan over medium heat",
                "Pour batter to form pancakes",
                "Cook until bubbles form on surface, then flip",
                "Serve hot with butter and maple syrup",
            ],
            "cooking_tips": "Don't overmix batter - lumps are fine",
        },
    },
]
